#+OPTIONS: toc:nil author:nil title:nil date:nil
#+BIND: org-export-latex-title-command ""
#+Title:
#+LaTeX_CLASS: resume
#+LaTeX_CLASS_OPTIONS: [11pt,margin,centered]
#+LaTeX_HEADER: \setlength{\textwidth}{5.1in} % set width of text portion
# %\usepackage{helvetica} % uses helvetica postscript font (download helvetica.sty)
# %\usepackage{newcent}   % uses new century schoolbook postscript font 

# Center the name over the entire width of resume:
 \moveleft.5\hoffset\centerline{\large\bf Matthew T. Stickney}
# Draw a horizontal line the whole width of resume:
 \moveleft\hoffset\vbox{\hrule width\resumewidth height 1pt}\smallskip
# address begins here
# Again, the address lines must be centered over entire width of resume:
 \moveleft.5\hoffset\centerline{165 Mountfort rd}
 \moveleft.5\hoffset\centerline{North Yarmouth, ME 04097}
 \moveleft.5\hoffset\centerline{(207) 542-7157}

\begin{resume}
* Summary of Qualifications
Polyglot programmer with experience in a variety of programming
languages and paradigms. Deliberate, pragmatic, and focused on getting
the job done, robustly. Has a broad range of knowledge and can stare a
computer down at 20 yards. Skilled debugger; maintainer at heart.

** COMMENT spares
GIS analysis and development, and experience using
and developing tools for industry-standard GIS software.

with a strong backaground in mathematics and formal logic. Able to work both
independently and as part of a team, and to rapidly acquire new skills. Excellent
analytical abilities. Commitment to creating elegant, robust, and extensible
solutions to complex problems.

* Skills and Accomplishments
  - Designed public system API to support third-party system integrations
  - Developed internal tooling for automatic builds, database schema
    management, and to simplify deployment processes
  - Developed a micro-ORM library
  - Created module for dynamically-managed marketing and customer
    communication mailings
  - Added SMS messaging support to existing marketing module
  - Implemented flagship feature for real-time communication with
    customers at POS stations
  - Worked with management to assess technical risk and prioritize
    developer resources to meet current needs
  - Conducted developer and support training for new systems and
    technology
  - Set long-term modernization technology goals, conducted training
  - Advanced debugging techniques (system tracing, low-level
    debuggers, binary analysis, packet traces)

** COMMENT alternatives
  - Developed tools to simplify troubleshooting and deployment for
    support technicians
  - Developed tools to manage database schema changes during upgrades

** COMMENT old
  - Co-authored lightweight RPC protocol specification
  - Wrote client library and threaded server framework for the above
  - Implemented a web-based document compilation service for
    intra-office use
  - Implemented a static analysis tool in Python to detect unused code
    in a legacy project
  - Wrote runtime polymorphic multimethod library for Python
  - Wrote Smalltalk-like object system for TCL
  - Wrote virtual memory management subsystem for an emulated
    multitasking OS, solo, in less than 24 hours.
  - Wrote prototype integration of NMap into a network device test suite.
  - Ran extracurricular seminar on Computer Science topics with three other students.
  - Invited to join the Upsilon Pi Epsilon computer science honors society.

** COMMENT spares
  - Created a specialized label printing tool in Javascript in one day with no
    prior experience with the language.
  - Led student development of emulated multitasking operating system,
    integrating code from multiple contributors.
  - Wrote sparse Lisp implementation in PHP with macro support (FEXPRs)
  - Led team of four students during class project, initiating code review
    process and completing the project early.
  - Wrote a program to parse and render robotic interior mapping data from
    scratch in one week.
  - Wrote ArcMap plugin to automate GIS data attribution, allowing the project
    to be completed ahead of schedule.
  - Worked independently to complete several additional GIS projects early
    with minimal supervision.
  - Created full spec and implementation for generic character-separated-value
    library in under three weeks, while enrolled full-time as a student.
  - Learned (X)HTML, CSS, PHP, and Javascript in approximately two weeks.
  - Self-taught a variety of programming languages from several paradigms
    (imperative, object-oriented, functional).
  - Ported Firefox extension for simplifying the GMail interface to the
    Chromium browser.

* Experience
Senior Software Developer, Maineline Technology Group, /2012-2018/ \\
Software Developer, QACafe, /Summer 2011/ \\
GIS Analyst/Software Developer, Penobscot Bay Media, LLC, /Summer 2008/

* Education
B.S. in Computer Science, University of Maine, Orono, ME (/Spring 2011/) \\
Dean's List at University of Maine, (/Fall 2009 & Spring 2010/) \\
Dean's List at Rensselaer Polytechnic Institute, (/2008/) \\
Maine School of Science and Mathematics, (/2004-2007/)

* Computer Skills
  - Languages: C\#, Python, C, Common Lisp, Go, Javascript, SQL
  - Software: ASP.NET, PostgreSQL, Apache, nginx, Subversion, Git
  - Other Technologies: HTML, CSS, AJAX, low-level COM, \LaTeX
\end{resume}
\center\emph{References available on request}
